/**
 * Scripts/configure-secrets.js
 * Purpose: Inject unprefixed environment variables into the Vite build substrate.
 * Authority: TS-Λ3 | v1.2.5 (Sovereign Sync)
 * Context: Harbor B (Mothership)
 */

const fs = require('fs');
const path = require('path');

// Target file is located in the root directory relative to this script
const targetPath = path.join(__dirname, '../.env');

/**
 * Authoritative list of environment variables (Unprefixed).
 * Matches the names saved in your GitHub Organization.
 */
const secretKeys = [
  'PERPLEXITY_API_KEY',
  'NOTION_API_KEY',
  'GEMINI_API_KEY',
  'GOOGLE_CLIENT_ID_GOV',
  'NOTION_PAGE_ID',
  'FIREBASE_API_KEY',
  'FIREBASE_APP_ID',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_MESSAGING_SENDER_ID'
];

console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('  INITIATING SECRET INJECTION (Direct Sync)');
console.log('  Model: RPR-SECRET-MODEL-V2');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

let envContent = '# GENERATED BY CONFIGURATION UTILITY (v1.2.5)\n';
envContent += `# TIMESTAMP: ${new Date().toISOString()}\n\n`;

let latchedCount = 0;
let missingKeys = [];

secretKeys.forEach(key => {
  const value = process.env[key];
  if (value) {
    // Vite requires VITE_ prefix for client-side access
    const viteKey = `VITE_${key}`;
    
    envContent += `${viteKey}="${value}"\n`;
    envContent += `${key}="${value}"\n`; // Maintain original key for node scripts
    
    console.log(`✅ [LATCHED] ${key} -> ${viteKey}`);
    latchedCount++;
  } else {
    console.log(`⚠️  [MISSING] ${key}`);
    missingKeys.push(key);
  }
});

/**
 * Synthesis: VITE_RPR_FIREBASE_CONFIG
 * Merges individual Firebase secrets into a JSON string for React consumption.
 */
if (process.env.FIREBASE_API_KEY && process.env.FIREBASE_APP_ID) {
  const config = {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: "rpr-corporate-site",
    storageBucket: "rpr-corporate-site.firebasestorage.app",
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID
  };
  envContent += `VITE_RPR_FIREBASE_CONFIG='${JSON.stringify(config)}'\n`;
  console.log('✅ [LATCHED] Synthesized VITE_RPR_FIREBASE_CONFIG');
}

try {
  fs.writeFileSync(targetPath, envContent);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`  [SUCCESS] ${latchedCount} secrets injected into .env`);
  console.log(`  Target Path: ${targetPath}`);
  
  if (missingKeys.length > 0) {
    console.log('\n  ⚠️  STRIKE WARNING: Missing Infrastructure Fuel:');
    missingKeys.forEach(k => console.log(`     - ${k}`));
  }
  
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
} catch (error) {
  console.error(`\n❌ [FATAL] Failed to write environment substrate: ${error.message}`);
  process.exit(1);
}